/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;

import net.unicon.idp.AttributeToMemcacheAction;

import static org.junit.Assert.*;

public class LibraryTest {
}
